"""create table books

Revision ID: 03896b59a5fb
Revises: ceef9d0d58e1
Create Date: 2022-03-27 10:20:45.837719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03896b59a5fb'
down_revision = 'ceef9d0d58e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_on', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_on', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('authors', sa.String(length=200), nullable=True),
    sa.Column('publisher', sa.String(length=120), nullable=True),
    sa.Column('publication_date', sa.Date(), nullable=True),
    sa.Column('category', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('books')
    # ### end Alembic commands ###
