"""create table readers

Revision ID: 7771d6f713db
Revises: 
Create Date: 2022-03-13 12:37:08.735082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7771d6f713db'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('readers',
    sa.Column('id', sa.Integer(), nullable=False),
    #sa.Column('firstname', sa.String(length=80), nullable=False),
    #sa.Column('lastname', sa.String(length=80), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=120), nullable=False),
    sa.Column('status', sa.Boolean(), default=True, server_default="true", nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username'))
    
    op.create_table('readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer, nullable=True),  #TODO: Update it to foreign key after books table ready.
    sa.Column('reader_id', sa.Integer,  sa.ForeignKey("readers.id")),
    sa.Column('rating', sa.Integer, nullable=True),
    sa.Column('review', sa.Text, nullable=True),
    sa.Column('read_date', sa.Date, nullable=True),
    sa.Column('has_read', sa.Boolean, default=False, server_default="false", nullable=True),
    sa.PrimaryKeyConstraint('id'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('readers')
    op.drop_table('readings')
    # ### end Alembic commands ###
