"""create table goals

Revision ID: a7e483aecd3d
Revises: f91d59241c57
Create Date: 2022-04-17 09:25:15.400857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7e483aecd3d'
down_revision = 'f91d59241c57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userid', sa.String(length=80), nullable=False),
    sa.Column('month', sa.String(length=10), nullable=False),
    sa.Column('goal_num', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['userid'], ['readers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('goals')
    # ### end Alembic commands ###
