"""create table readings

Revision ID: acdf0725a5e3
Revises: 7771d6f713db
Create Date: 2022-03-30 22:18:20.709937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acdf0725a5e3'
down_revision = '7771d6f713db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.Column('reader_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Float(precision=2), nullable=True),
    sa.Column('review', sa.Text(), nullable=True),
    sa.Column('last_update_review_rating_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('has_read', sa.Boolean(), nullable=True),
    sa.Column('last_update_read_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['reader_id'], ['readers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('readings')
    # ### end Alembic commands ###
