"""create table readings

Revision ID: b595589def06
Revises: 3a9fe02a9ccb
Create Date: 2022-03-30 22:18:20.709937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b595589def06'
down_revision = '3a9fe02a9ccb'
branch_labels = None
depends_on = None


def upgrade():
    # # ### commands auto generated by Alembic - please adjust! ###
    # this is old migration from Yixi
    # op.create_table('readings',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('created_on', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    # sa.Column('updated_on', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    # sa.Column('book_id', sa.Integer(), nullable=True),
    # sa.Column('reader_id', sa.Integer(), nullable=False),
    # sa.Column('rating', sa.Float(precision=2), nullable=True),
    # sa.Column('review', sa.Text(), nullable=True),
    # sa.Column('last_update_review_rating_at', sa.DateTime(timezone=True), nullable=True),
    # sa.Column('has_read', sa.Boolean(), nullable=True),
    # sa.Column('last_update_read_at', sa.DateTime(timezone=True), nullable=True),
    # sa.ForeignKeyConstraint(['reader_id'], ['readers.id'], ),
    # sa.PrimaryKeyConstraint('id')
    # )
    op.create_table('readings',
    sa.Column('created_on', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_on', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('volume_id', sa.String(length=20), nullable=False),
    sa.Column('reader_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Float(precision=2), nullable=True),
    sa.Column('review', sa.Text(), nullable=True),
    sa.Column('last_update_review_rating_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('has_read', sa.Boolean(), nullable=True),
    sa.Column('last_update_read_at', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['reader_id'], ['readers.id'], ),
    sa.ForeignKeyConstraint(['volume_id'], ['book_details.volume_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('readings')
    # ### end Alembic commands ###
